### ISSUE TITLE
*Question/Clarification?* Using Online/Vanilla

### ISSUE THREAD

**Issue by j-6-w3n7w027h** [xNicklaj/EldenBackup#3]
In the readme it states that the seamless co-op tag is set true because it's intended for the mod, and can break quest triggers. 
Please clarify, what does this mean? Should the mod not be used for online/vanilla play?

**Comment by xNicklaj** [comment]
You can use it for normal gameplay (.sl2 files) by setting UseSeamlessCoop to false.

The tool was designed for seamless coop but you can use it with (.sl2 too),
